# Site settings
title: Vox Product Code of Conduct
email: support@voxmedia.com
description: > # This code of conduct governs the environment of the Vox Product team.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://code-of-conduct.voxmedia.com" # the base hostname & protocol for your site
twitter_username: voxproduct
github_username:  voxmedia

# Build settings
markdown: kramdown
